- name: "Set AMD '{{ driver_file }}' driver to load on startup in {{ cfg_video_freebsd_rc_conf_filepath }}"
  # Check if drm-kmod properly loaded at boot with 'dmesg | grep drm'
  community.general.sysrc:
    path: "{{ cfg_video_freebsd_rc_conf_filepath }}"
    name: "kld_list"
    value: "{{ driver_file }}"
    state: value_present
  vars:
    driver_file: "{{ 'radeonkms' if (cfg_video_card_series == 'GCN_1_2') else 'amdgpu' }}"
  become: true
  become_user: root

