- name: "Set AMD '{{ driver_file }}' driver to load on startup in {{ rc_conf_filepath }}"
  # Check if drm-kmod properly loaded at boot with 'dmesg | grep drm'
  community.general.sysrc:
    path: "{{ rc_conf_filepath }}"
    name: "kld_list"
    value_present: "{{ driver_file }}"
    state: present
  vars:
    driver_file: "{{ 'radeonkms' if (video_card_series == 'GCN_1_2') else 'amdgpu' }}"
  become: true
  become_user: root

