- name: "Set Intel '{{ driver_file }}' driver to load on startup in {{ rc_conf_filepath }}"
  # Check if drm-kmod properly loaded at boot with 'dmesg | grep drm'
  community.general.sysrc:
    path: "{{ rc_conf_filepath }}"
    name: "kld_list"
    value: "{{ driver_file }}"
    state: present
  vars:
    driver_file: "i915kms"
  become: true
  become_user: root

