# See FreeBSD Handbook instructions:
#   https://wiki.freebsd.org/Graphics#Hardware_Support
# Also supplementary instructions here:
#   https://docs.freebsd.org/en/books/handbook/x11/#x-install
#   https://freebsddesktop.github.io/2019/03/11/xorg-quickstart.html

- name: "Install 'gpu-firmware-kmod' package (collection of AMD/Nvidia/Intel card firmwares)"
  ansible.builtin.package:
    name: 'gpu-firmware-kmod'
    state: present
  become: true
  become_user: root

# Note: Workaround for FreeBSD 14.2 failure to wire up drm-kmod packages.
#       Per release errata, solution is to build manually.
# Ref:  https://www.freebsd.org/releases/14.2R/errata/#open-issues
# - name: "Install 'drm-kmod' package, which contains both Intel and AMD drivers"
- name: "Build and install 'graphics/drm-61-kmod' package from source, to resolve FreeBSD 14.2 bug"
  community.general.portinstall:
    name: 'graphics/drm-61-kmod'
    state: present
    use_packages: false
  become: true
  become_user: root

- name: "Configure Intel video card hardware acceleration"
  ansible.builtin.include_tasks: intel.yml
  when: cfg_video_card_make == "Intel"

- name: "Configure AMD video card hardware acceleration"
  ansible.builtin.include_tasks: amd.yml
  when: cfg_video_card_make == "AMD"

