- name: "Configure Intel video card Vulkan support"
  ansible.builtin.include_tasks: intel.yml
  when: cfg_video_card_make == "Intel"

- name: "Configure AMD video card Vulkan support"
  ansible.builtin.include_tasks: amd.yml
  when: cfg_video_card_make == "AMD"

