# See ArchWiki instructions for Intel video-decode accel driver types:
#   https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Intel

- name: "Install Intel HD-series video card driver for video encode/decode accel"
  community.general.pacman:
    name: intel-media-driver
    state: present
  become: true
  become_user: root
  when: video_card_series == 'HD'

- name: "Install Intel GMA-series video card driver for video encode/decode accel"
  community.general.pacman:
    name: libva-intel-driver
    state: present
  become: true
  become_user: root
  when: video_card_series == 'GMA'

