- name: "Abort if cfg_video_card_make not 'Intel' or 'AMD'"
  ansible.builtin.fail:
    msg: "cfg_video_card_make var must be 'Intel' or 'AMD'"
  when: (cfg_video_card_make != 'Intel') and
        (cfg_video_card_make != 'AMD')

- name: "Abort if Intel cfg_video_card_series not 'GMA' or 'HD'"
  ansible.builtin.fail:
    msg: "Intel cfg_video_card_series var must be 'GMA' or 'HD'"
  when: (cfg_video_card_make == 'Intel') and
        (cfg_video_card_series != 'GMA') and
        (cfg_video_card_series != 'HD')

- name: "Abort if AMD cfg_video_card_series not 'GCN_1_2' or 'GCN_3_4_5_RDNA'"
  ansible.builtin.fail:
    msg: "AMD cfg_video_card_series var must be 'GCN_1_2' or 'GCN_3_4_5_RDNA'"
  when: (cfg_video_card_make == 'AMD') and
        (cfg_video_card_series != 'GCN_1_2') and
        (cfg_video_card_series != 'GCN_3_4_5_RDNA')

