# See ArchWiki instructions for AMD 2D/3D hardware acceleration:
#   https://wiki.archlinux.org/index.php/Xorg#Driver_installation
#   https://wiki.archlinux.org/index.php/Xorg#AMD
#   https://wiki.archlinux.org/index.php/AMDGPU#Installation
#   https://wiki.archlinux.org/index.php/ATI#Installation

- name: "Install main AMD ATI video card driver for Xorg 2D acceleration"
  community.general.pacman:
    name: xf86-video-ati
    state: present
  become: true
  become_user: root
  when: cfg_video_card_series == "GCN_1_2"

- name: "Install main AMD AMDGPU video card driver for Xorg 2D acceleration"
  community.general.pacman:
    name: xf86-video-amdgpu
    state: present
  become: true
  become_user: root
  when: cfg_video_card_series == "GCN_3_4_5_RDNA"

- name: "Install AMD video card driver for OpenGL 3D acceleration"
  community.general.pacman:
    name: mesa
    state: present
  become: true
  become_user: root

- name: "Install AMD video card drivers for video encode/decode accel"
  community.general.pacman:
    name:
      - libva-mesa-driver
      - mesa-vdpau
    state: present
  become: true
  become_user: root

