# See ArchWiki instructions for Intel 2D/3D hardware acceleration:
#   https://wiki.archlinux.org/index.php/Intel_graphics#Installation
#   https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Intel
#   https://wiki.archlinux.org/index.php/Xorg#Driver_installation

- name: "Install main Intel video card driver for Xorg 2D acceleration"
  community.general.pacman:
    name: xf86-video-intel
    state: present
  become: true
  become_user: root

- name: "Install Intel video card driver for OpenGL 3D acceleration"
  community.general.pacman:
    name: mesa
    state: present
  become: true
  become_user: root

- name: "Install Intel HD-series video card driver for video encode/decode accel"
  community.general.pacman:
    name: intel-media-driver
    state: present
  become: true
  become_user: root
  when: video_card_series == 'HD'

- name: "Install Intel GMA-series video card driver for video encode/decode accel"
  community.general.pacman:
    name: libva-intel-driver
    state: present
  become: true
  become_user: root
  when: video_card_series == 'GMA'

